//@version=4
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Greeffer
// 04-11-2020: 58% profit in backtests trading BTCUSDTPERP on 15m time frame (no leverage). Lower risk, higher time frome - good compromise.

strategy("Greeffer BB Strategy", "Greeffer", false, format=format.price, scale=scale.right, precision=2, pyramiding=10, default_qty_type=strategy.percent_of_equity, default_qty_value=15, initial_capital=1000, currency=currency.USD, commission_type=strategy.commission.percent, commission_value=0.075, process_orders_on_close=true)

source = close
length = input(20, minval=1)
mult = input(2.0, minval=0.001, maxval=50)

basis = sma(source, length)
dev = mult * stdev(source, length)

upper = basis + dev
lower = basis - dev

if (crossover(source, upper))
    strategy.entry("sell", strategy.short, comment="sell", when=rsi(close, 14)>80)
    strategy.close("sell", when=crossunder(source, lower), comment = "close sell")
    
if (crossunder(source, lower))
    strategy.entry("buy", strategy.long, oca_name="BollingerBands", comment="buy", when=rsi(close, 14)>30)
    strategy.close("buy", when=crossover(source, upper), comment = "close buy")
    
//strategy.risk.max_drawdown(3, strategy.percent_of_equity) // set maximum drawdown to 50% of maximum equity
//strategy.close_all(when= , comment="close all")

plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)