// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Greeffer

//@version=4
//study("RSI/BB 1minute Study", shorttitle="BBW/RSI/1m", precision=5)
strategy("RSI/BB 1minute Study", "BBW/RSI/1m", false, format=format.inherit, 
     scale=scale.right, precision=5, pyramiding=20, default_qty_type=strategy.percent_of_equity,
     default_qty_value=100, initial_capital=100000, currency=currency.USD,
     commission_type=strategy.commission.percent, commission_value=0.075,
     process_orders_on_close=true, calc_on_every_tick=false)

// R S I
source = close
sell = input(title="Sell", defval=75, minval=0, maxval=100)
buy = input(title="Buy", defval=34, minval=0, maxval=100)
length = input(title="Length", defval=14, minval=1, maxval=500)
myRsi = rsi(source, length)
plot(myRsi, title="myRsi", color=color.blue, linewidth=2, style=plot.style_line, transp=70)
hline(buy, title='buy', color=color.red, linestyle=hline.style_dotted, linewidth=1)
hline(sell, title='sell', color=color.red, linestyle=hline.style_dotted, linewidth=1)

// B o l i n g e r   B a n d s 
//bBands = bb(close, length, mult)
[middle, upper, lower] = bb(source, length, 2)
plot(middle, title="middle", color=color.red, display=display.none)
plot(upper, title="upper", color=color.green, display=display.none)
plot(lower, title="lower", color=color.green, display=display.none)

// B o l l i n g e r  B a n d  W i d t h 
bbWidth = bbw(source, length, 2)
plot(bbWidth, title="bbWidth", color=color.orange, display=display.none)

// S t r a t e g i e s

if (crossunder(source, lower) and crossunder(myRsi, buy))
    strategy.entry("long0", strategy.long,stop=strategy.position_avg_price +
         strategy.position_avg_price*0.1, oca_name="long0",
         oca_type=strategy.oca.reduce)
    strategy.exit("longo", oca_name="long0", qty_percent=100, stop=strategy.position_avg_price +
         strategy.position_avg_price*0.1, trail_price=middle, trail_offset=2)
    //strategy.close(id, when, comment, qty, qty_percent) 
    //strategy.close("short0", when=source<lower, qty_percent=100)

if(bbWidth <= 0.00260)
    strategy.entry("bbWidth0", strategy.long, stop=strategy.position_avg_price +
         strategy.position_avg_price*0.1, oca_name="long0", oca_type=strategy.oca.reduce)
    strategy.exit("bbWidth0", oca_name="long0", qty_percent=100, stop=strategy.position_avg_price +
         strategy.position_avg_price*0.1, trail_price=middle, trail_offset=5, when=crossover(myRsi, sell))
    
if (crossover(source, upper)and crossover(myRsi, sell))
    strategy.entry("short0", strategy.short, stop=strategy.position_avg_price +
         strategy.position_avg_price*0.1, oca_name="long0", oca_type=strategy.oca.reduce)
    strategy.exit("short0", oca_name="long0", qty_percent=100, stop=strategy.position_avg_price +
         strategy.position_avg_price*0.1, trail_price=middle, trail_offset=2)
    //strategy.close("long0",when=source>upper, qty_percent=100)

// A l e r t c o n d i t i o n s 
//alertcondition(crossunder(myRsi, buy) and crossunder(close, lower), title='Buy', message='{"direction":"buy","ticker":"{{ticker}}","frame":"1minute","close":"{{close}}","time":"{{time}}"}')
//alertcondition(crossover(myRsi, sell) and crossover(close, upper), title='Sell', message='{"direction":"sell","ticker":"{{ticker}}","frame":"1minute","close":"{{close}}","time":"{{time}}"}')
